### ISSUE TITLE
Exception when number of worker process is more than one

### ISSUE THREAD

**Issue by Sunoyon** [awslabs/kinesis-storm-spout#1]
Hi

When I raised the number of worker process to more than one (topoConf.setNumWorkers(4);) I faced an exception. Could you please help me out?

I've tried both in local mode and remote mode (aws cluster). In both way I faced the same problem in spout.

Exception message: 
java.lang.RuntimeException: java.lang.RuntimeException: java.io.NotSerializableException: java.nio.HeapByteBuffer
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:90) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:61) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:62) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.disruptor$consume_loop_STAR_$fn__2975.invoke(disruptor.clj:74) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.util$async_loop$fn__444.invoke(util.clj:403) ~[storm-core-0.9.0.1.jar:na]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]
Caused by: java.lang.RuntimeException: java.io.NotSerializableException: java.nio.HeapByteBuffer
    at backtype.storm.serialization.SerializableSerializer.write(SerializableSerializer.java:24) ~[storm-core-0.9.0.1.jar:na]
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:554) ~[kryo-2.17.jar:na]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:77) ~[kryo-2.17.jar:na]
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18) ~[kryo-2.17.jar:na]
    at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:472) ~[kryo-2.17.jar:na]
    at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:27) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:27) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.daemon.worker$mk_transfer_fn$fn__5686$fn__5690.invoke(worker.clj:108) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.util$fast_list_map.invoke(util.clj:801) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.daemon.worker$mk_transfer_fn$fn__5686.invoke(worker.clj:108) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.daemon.executor$start_batch_transfer__GT_worker_handler_BANG_$fn__3328.invoke(executor.clj:240) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.disruptor$clojure_handler$reify__2962.onEvent(disruptor.clj:43) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:87) ~[storm-core-0.9.0.1.jar:na]
    ... 6 common frames omitted
Caused by: java.io.NotSerializableException: java.nio.HeapByteBuffer
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1165) ~[na:1.6.0_65]
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1535) ~[na:1.6.0_65]
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.6.0_65]
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1413) ~[na:1.6.0_65]
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1159) ~[na:1.6.0_65]
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:329) ~[na:1.6.0_65]
    at backtype.storm.serialization.SerializableSerializer.write(SerializableSerializer.java:21) ~[storm-core-0.9.0.1.jar:na]
    ... 18 common frames omitted

**Comment by Alireza-** [comment]
Hi,
I ran into the same problem when I set the number of workers to more than 1 in the following topology:
https://github.com/awslabs/aws-big-data-blog/blob/master/aws-blog-kinesis-storm-clickstream-app/src/main/java/KinesisStormClickstreamApp/SampleTopology.java
Just wondering if I have to add new serializer to the above application or I need to update the kinesis-storm-spout project and just register the serializer to the above topology?

Thanks

**Comment by nehavishnoi11** [comment]
Hi Frank,
i also stuck in the same problem with kinesis record.f you dont mind can you please share your  KinesisRecordScheme implementation?

**Comment by fjania** [comment]
Certainly

```java
import java.util.ArrayList;
import java.util.List;

import backtype.storm.tuple.Fields;

import com.amazonaws.services.kinesis.model.Record;
import com.amazonaws.services.kinesis.stormspout.IKinesisRecordScheme;

public class KinesisStringScheme implements IKinesisRecordScheme {
	private static final long serialVersionUID = 1L;
	/**
	 * Name of the (partition key) value in the tuple.
	 */
	public static final String FIELD_PARTITION_KEY = "partitionKey";
	/**
	 * Name of the (Kinesis record) value in the tuple.
	 */
	public static final String FIELD_RECORD = "record";

	@Override
	public List<Object> deserialize(Record record) {
		final List<Object> l = new ArrayList<>();
		l.add(record.getPartitionKey());
		l.add(new String(record.getData().array()));
		return l;
	}

	@Override
	public Fields getOutputFields() {
		return new Fields(FIELD_PARTITION_KEY, FIELD_RECORD);
	}

}
```

**Comment by nehavishnoi11** [comment]
Thanks Frank i also used the same kinesisrecordScheme and it worked for me.so far the topology is working fine for multiple worker processes.
