### ISSUE TITLE
 Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by mrdlmndr** [awslabs/kinesis-storm-spout#14]
Hello Awslabs team,

I have configure the ~/.aws/credentials files with my AWS credentials.
Still I'm getting following exception:

9503 [Thread-21-kinesis-entry] ERROR backtype.storm.util - Async loop died!
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2460) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:860) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at com.amazonaws.services.kinesis.stormspout.KinesisHelper.getShardList(KinesisHelper.java:85) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at com.amazonaws.services.kinesis.stormspout.state.zookeeper.ZookeeperStateManager.activate(ZookeeperStateManager.java:109) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at com.amazonaws.services.kinesis.stormspout.KinesisSpout.activate(KinesisSpout.java:125) ~[kinesis-storm-clickstream-sample-app-1.0.0-jar-with-dependencies.jar:na]
	at backtype.storm.daemon.executor$fn__4654$fn__4669$fn__4698.invoke(executor.clj:563) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.util$async_loop$fn__458.invoke(util.clj:463) ~[storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

I have tried with manually export my credentials. But then, it only work for LocalMode Storm Topology, not for RemoteMode Topology.

Thanks.

**Comment by matrix10657** [comment]
The credentials are not accessed until the spout is `open`ed -- they aren't fetched on your local machine and *then* transmitted to the remote host. When running w/ a RemoteMode topology, this means that you will have to have setup ~/.aws/credentials on the remote hosts that can possibly run the spout so they can be fetched.

The way the [Sample](https://github.com/awslabs/kinesis-storm-spout/tree/master/src/main/samples) gets around this is with the CustomCredentialsProviderChain that looks for a properties file in the classpath with the credentials. I assume this gets packaged with the uber-jar which *does* get sent to the remote hosts so it can be loaded there.

**Comment by mrdlmndr** [comment]
Thank for reply. That error has been solved.

For RemoteMode, ZookeeperStateManager's activate() function is not calling, where for localmode it works fine.

For Local Mode, it is showing following logs but not for RemoteMode:
7910 [Thread-11-kinesis-entry] INFO  com.amazonaws.services.kinesis.stormspout.state.zookeeper.ZookeeperStateManager - ZookeeperStateManager[taskIndex=0]Activating with shardList [shardId-000000000000]
7916 [Thread-11-kinesis-entry] INFO  com.amazonaws.services.kinesis.stormspout.state.zookeeper.ZookeeperShardState - ShardList already initialized in Zookeeper. Assuming it is valid.
8035 [Thread-11-kinesis-entry] INFO  com.amazonaws.services.kinesis.stormspout.state.zookeeper.ZookeeperStateManager - ZookeeperStateManager[taskIndex=0] Got shardList: [shardId-000000000000]
8040 [Thread-11-kinesis-entry] INFO  com.amazonaws.services.kinesis.stormspout.KinesisShardGetter - Seeking to com.amazonaws.services.kinesis.stormspout.ShardPosition@5fa69521[pos=AFTER_SEQUENCE_NUMBER,sequenceNum=49549772487587189730655947986881820141424175515644723202]
8399 [Thread-11-kinesis-entry] INFO  com.amazonaws.services.kinesis.stormspout.state.zookeeper.ZookeeperStateManager - ZookeeperStateManager[taskIndex=0] got getter assignment. Handling [BufferedGetter[getter=KinesisShardGetter[shardId=shardId-000000000000]]].

My config.properties file:
   initialPositionInStream = LATEST
   zookeeperEndpoint = localhost:2181
   zookeeperPrefix = kinesis_spout
