### ISSUE TITLE
when I run this I get error "Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider" 

### ISSUE THREAD

**Issue by nehavishnoi11** [awslabs/kinesis-storm-spout#25]
I'm trying to run against a AWS Kinesis stream, and I've included my AWSCredentials.properties file in the same directory where sample.properties file is.

I've examined , reviewed packaged jar file and the file is present , exists in packaged jar file com/amazonaws/auth/AWSCredentialsProvider

Below is error message. Any and all replies are appreciated!!

Neha

ns-lang-2.5.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/jetty-util-6.1.26.jar:/opt/storm/lib/disruptor-2.10.1.jar:KinesisStormSpout14.jar:/opt/storm/conf:/opt/storm/bin -Dstorm.jar=KinesisStormSpout14.jar SampleTopology sample.properties RemoteMode Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Class.java:2570) at java.lang.Class.getMethod0(Class.java:2813) at java.lang.Class.getMethod(Class.java:1663) at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494) at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486) Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 6 more [vagrant@supervisor1 shared]$ Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentialsProvider

**Comment by abshkd** [comment]
I saw the same problem. Realized I copied Maven dependency as ```provided``` but it should be ```compiled``` as it will go into your uber jar
