### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazonaws/util/json/JSONObject

### ISSUE THREAD

**Issue by kranthisai** [awslabs/kinesis-storm-spout#35]
I am getting the following exception. May i know the reason.

java.lang.NoClassDefFoundError: com/amazonaws/util/json/JSONObject
	at com.amazonaws.services.kinesis.leases.impl.Lease.toString(Lease.java:229)
	at java.lang.String.valueOf(String.java:2849)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseIfNotExists(LeaseManager.java:281)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:127)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:395)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:330)

**Comment by twosider** [comment]
This looks like you are using the Kinesis Client Library (KCL) with AWS Java SDK 1.11. KCL still requires 1.10.

**Comment by kranthisai** [comment]
Oh ok. Let me try, Thank you. I am using AWS java SDK 1.11

**Comment by kranthisai** [comment]
Thank you. I got it.
